# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7f3f81581e6f7c30af48547377ad01ac4414db91dbd9c2aa44bd2618c15822af0d143a14e940bfae23997dfb47cd2cc3f3fadaab1ed8aadda4071d8b27a0a7

test:
  secret_key_base: 335b97a6a732d5ae3dbfcb723d4a5362924b0aa46b5fcbac9fa5a6c08247c55b427187de065c8bd829e1f9ce6cc9b39c540a338d8a1deacbd80421dcd189f996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
